USE [master]
GO

/****** Object:  Database [CashControl]    Script Date: 28/06/2024 09:25:11 ******/
CREATE DATABASE [CashControl]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CashControl', FILENAME = N'C:\Users\2222120\CashControl.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CashControl_log', FILENAME = N'C:\Users\2222120\CashControl_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CashControl].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CashControl] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CashControl] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CashControl] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CashControl] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CashControl] SET ARITHABORT OFF 
GO

ALTER DATABASE [CashControl] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CashControl] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CashControl] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CashControl] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CashControl] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CashControl] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CashControl] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CashControl] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CashControl] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CashControl] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CashControl] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CashControl] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CashControl] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CashControl] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CashControl] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CashControl] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CashControl] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CashControl] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CashControl] SET  MULTI_USER 
GO

ALTER DATABASE [CashControl] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CashControl] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CashControl] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CashControl] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CashControl] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CashControl] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CashControl] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CashControl] SET  READ_WRITE 
GO

